name: dart_fuse
description: Dart FFI bindings for FUSE
version: 0.0.1
homepage: https://github.com/maks/dart_fuse

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
