name: dart_fuse
description: Dart FFI bindings for FUSE
version: 0.0.1-nullsafety.1
homepage: https://github.com/maks/dart_fuse

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  ffi: ^0.2.0-nullsafety.1

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
